name: Test WindeployQT

on:
  workflow_dispatch:

jobs:
  test-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.7.*'
        
      - name: Create test executable (dummy)
        run: |
          New-Item -ItemType Directory -Force -Path build
          # Create a minimal Windows executable
          [System.IO.File]::WriteAllText("build\ESL-PSC.exe", "This is a test executable")
        shell: pwsh
        
      - name: Test windeployqt
        shell: pwsh
        run: |
          windeployqt.exe build\ESL-PSC.exe --verbose 1 --release --compiler-runtime
          if (-not (Test-Path "build\Qt6Core.dll")) {
            Write-Error "windeployqt did not deploy Qt6Core.dll"
            exit 1
          }
          Write-Host "✅ windeployqt ran successfully and Qt6Core.dll found"

