name: Test WindeployQT

on:
  workflow_dispatch:

jobs:
  test-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Qt (libs + tools)
        run: choco install -y qt6-base-dev qt6-tools --params "/Path"
        shell: pwsh
        
      - name: Create test executable (dummy)
        run: |
          New-Item -ItemType Directory -Force -Path build
          # Create a minimal Windows executable
          [System.IO.File]::WriteAllText("build\ESL-PSC.exe", "This is a test executable")
        shell: pwsh
        
      - name: Test windeployqt
        shell: pwsh
        run: |
          # Locate windeployqt.exe installed by Chocolatey (path may vary by version)
          $wqt = Get-ChildItem -Path 'C:\Qt' -Filter windeployqt.exe -Recurse | Select-Object -First 1
          if (-not $wqt) {
            Write-Error 'windeployqt.exe not found after installing qt6-tools'
            exit 1
          }

          # Prepend directory to PATH and run it
          $env:PATH = "$($wqt.Directory.FullName);$env:PATH"
          & $wqt.FullName build\ESL-PSC.exe --verbose 1 --release --compiler-runtime
          
          # Verify the deployment
          if (Test-Path "build\Qt6Core.dll") {
            Write-Host "✅ windeployqt ran successfully!"
          } else {
            Write-Error "❌ windeployqt failed to deploy Qt libraries"
            exit 1
          }
