name: Test WindeployQT

on:
  workflow_dispatch:

jobs:
  test-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.7.*'
        
      - name: Create test executable (dummy)
        run: |
          New-Item -ItemType Directory -Force -Path build
          # Create a minimal Windows executable
          [System.IO.File]::WriteAllText("build\ESL-PSC.exe", "This is a test executable")
        shell: pwsh
        
      - name: Verify windeployqt availability
        shell: pwsh
        run: |
          $pathExe = (Get-Command windeployqt.exe -ErrorAction Stop).Source
          Write-Host "Found windeployqt at $pathExe"
          & $pathExe --version
          Write-Host "✅ windeployqt is available and runnable"

